In [3]:
#Q1.Write a NumPy program to replace the negative values in a NumPy array with 0.

import numpy as np

arr = np.array([-1, 2, -3, 4, -5])

# Replace negative values with 0
arr = np.clip(arr, 0, None)

print(arr)


[0 2 0 4 0]


In [4]:
import numpy as np
arr = np.array([-1, 2, -3, 4, -5])

# Replace negative values with 0
arr = np.where(np.less(arr,0),0,arr)

print(arr)


[0 2 0 4 0]


In [5]:
#Q2.Write a NumPy program to replace all elements of a NumPy array that are greater than the
##    specified array.[Expected Output:
#Original array:
#          [[ 0.42436315 0.48558583 0.32924763]
#           [ 0.7439979 0.58220701 0.38213418]
#           [ 0.5097581 0.34528799 0.1563123 ]]
#  Replace all elements of the said array with .5 which are greater than. 5
#           [[ 0.42436315 0.48558583 0.32924763]
#           [ 0.5 0.5 0.38213418]
#           [ 0.5 0.34528799 0.1563123 ]]] 



import numpy as np

arr = np.array([[0.42436315, 0.48558583, 0.32924763],
                [0.7439979, 0.58220701, 0.38213418],
                [0.5097581, 0.34528799, 0.1563123]])

# Replace all elements greater than 0.5 with 0.5
arr = np.where(arr > 0.5, 0.5, arr)

print("Original array:")
print(arr)


Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [6]:
#Q3.Write a NumPy program to convert a NumPy array into Python list structure.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Convert NumPy array to Python list
python_list = arr.tolist()

print(python_list)


[1, 2, 3, 4, 5]


In [7]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])

# Convert NumPy array to Python list
python_list = arr.tolist()

print(python_list)


[[1, 2], [3, 4], [5, 6]]


In [8]:
#Q4.Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).
import numpy as np

# create an array of numbers between 0 and 10
arr = np.arange(11)

# shuffle the array
np.random.shuffle(arr)

print(arr)


[ 1  2  7 10  3  5  0  6  8  4  9]


In [9]:
import numpy as np
arr = np.arange(11)
np.random.permutation(arr)


array([ 1,  9,  3, 10,  8,  5,  0,  6,  2,  4,  7])

In [13]:
#Q5.Write a NumPy program to convert 1-D arrays as columns into a 2-D array.
##Sample array: (10,20,30), (40,50,60)
import numpy as np

# Sample 1-D arrays
array1 = np.array([10, 20, 30])
array2 = np.array([40, 50, 60])

# Convert 1-D arrays as columns into a 2-D array
result = np.column_stack((array1, array2))

print(result)


[[10 40]
 [20 50]
 [30 60]]


In [14]:
#You can also use the numpy.vstack() function to stack the 1-D arrays vertically and get the same 
##    result.
result = np.vstack((array1, array2)).T


In [15]:
#Q6.Write a NumPy program to concatenate two 2-dimensional arrays.
## Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]

import numpy as np

# Sample 2-dimensional arrays
array1 = np.array([[0, 1, 3], [5, 7, 9]])
array2 = np.array([[0, 2, 4], [6, 8, 10]])

# Concatenate two 2-dimensional arrays
result = np.concatenate((array1, array2), axis=0)

print(result)


[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]


In [16]:
#Q7.Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.
import numpy as np

# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.matrix(np.arange(5))
matrix = np.tile(matrix,(5,1))
print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [19]:
import numpy as np
matrix = np.matrix(np.arange(25)).reshape(5,5)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [20]:
matrix = np.zeros((5,5))
matrix = np.add(matrix, np.arange(5))
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [21]:
#Q8.Write a NumPy program to move axes of an array to new positions. Other axes remain in their 
##   original order.[Expected Output:
#     (3, 4, 2)
#     (4, 2, 3)]

import numpy as np

# Create an array with shape (3, 4, 2)
arr = np.random.rand(3, 4, 2)

# Move axis 0 to position 2
result1 = np.moveaxis(arr, 0, 2)

# Move axis 2 to position 0
result2 = np.moveaxis(result1, 2, 0)

print(result1.shape)
print(result2.shape)


(4, 2, 3)
(3, 4, 2)


In [23]:
#Q9.Write a NumPy program to view inputs as arrays with at least two dimensions, three dimensions.
import numpy as np

# Create a 1-D array
arr1d = np.array([1, 2, 3])

# View input as array with at least 2 dimensions
arr2d = np.atleast_2d(arr1d)

print(arr2d)
print(arr2d.shape)


# Create a 2-D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# View input as array with at least 3 dimensions
arr3d = np.atleast_3d(arr2d)

print(arr3d)
print(arr3d.shape)


[[1 2 3]]
(1, 3)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 3, 1)


In [24]:
#Q10.Write a NumPy program to create a 4x4 array, now create a new array from the said array
##  swapping first and last, second and third columns.
import numpy as np

# Create a 4x4 array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Create a new array by swapping first and last columns
result = np.array(arr[:,[3,1,2,0]])

print(result)


[[ 4  2  3  1]
 [ 8  6  7  5]
 [12 10 11  9]
 [16 14 15 13]]


In [25]:
#Q11.Write a NumPy program to multiply two given arrays of the same size element-by-element.
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Multiply the arrays element-by-element
result = np.multiply(arr1, arr2)

print(result)


[ 4 10 18]


In [26]:
#Q12.Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the
##  main diagonal.
import numpy as np

# Create a 4x4 matrix of zeros
matrix = np.zeros((4,4))
# Create a 4x4 identity matrix
eye = np.eye(4)
# Adding the identity matrix to the zeros matrix
matrix = matrix + eye
# Flipping the matrix
matrix = np.fliplr(matrix)

print(matrix)


[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [28]:
#Q13.Write a NumPy program to create a 3x3 identity matrix
import numpy as np

# Create a 3x3 identity matrix
matrix = np.eye(3)

print(matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
matrix = np.identity(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
#Q14.Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.
import numpy as np

# Create an array of 10 zeros
zeros = np.zeros(10)
# Create an array of 10 ones
ones = np.ones(10)
# Create an array of 10 fives
fives = np.full(10, 5)

# Create an array of zeros, ones, and fives
result = np.concatenate((zeros, ones, fives))

print(result)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [31]:
result = np.hstack((zeros, ones, fives))
print(result)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [32]:
#Q15.Write a NumPy program to get help on the add function.
import numpy as np

# Get help on the add function
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [33]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi